# Generated by Django 5.1.1 on 2024-09-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
