# Generated by Django 5.0.9 on 2024-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='is_proctored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='proctoring_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
