# Generated by Django 5.1.1 on 2024-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_studentassessmentattempt_user_submissions_and_more'),
        ('quiz', '0003_remove_studentanswer_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='quiz.answeroption'),
        ),
    ]
