# Generated by Django 5.1.1 on 2024-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
