# Generated by Django 5.1.1 on 2024-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_member_email_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
