# Generated by Django 5.1.1 on 2024-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_member_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
