# Generated by Django 5.1.1 on 2024-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Manager', 'Manager'), ('Member', 'Member')], max_length=10),
        ),
    ]
