# Generated by Django 5.0.9 on 2024-11-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_member_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='role_member',
        ),
    ]
