# Generated by Django 5.0.9 on 2024-10-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
