# Generated by Django 5.1.1 on 2024-10-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
