# Generated by Django 5.1.1 on 2024-10-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='random_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
