# Generated by Django 5.1.1 on 2024-10-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('module_group', '0004_alter_module_icon'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules assigned to this role.', related_name='role_modules', to='module_group.module', verbose_name='modules'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to this role.', related_name='role_permissions', to='auth.permission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
