# Generated by Django 5.0.9 on 2024-11-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_group', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.RemoveField(
            model_name='role',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_group.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role')),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
