# Generated by Django 5.1.1 on 2024-10-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_modules_role_permissions_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_delete_user', 'Can delete user')]},
        ),
    ]
