# Generated by Django 5.1.1 on 2024-10-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_delete_user', 'Can delete user'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user')]},
        ),
    ]
