# Generated by Django 5.1.1 on 2024-10-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_delete_user', 'Can delete user'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user'), ('can_export_users', 'Can export users'), ('can_import_users', 'Can import users')]},
        ),
    ]
