# Generated by Django 5.1.1 on 2024-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_group', '0003_alter_module_module_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
