# Generated by Django 5.1.1 on 2024-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
