# Generated by Django 5.1.1 on 2024-10-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student'),
        ),
    ]
