# Generated by Django 5.1.1 on 2024-10-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
