# Generated by Django 5.1.1 on 2024-10-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_student_student_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_delete_user', 'Can delete user')]},
        ),
    ]
